<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

</head>
<body>
<table class="table table-warning">
    <thead>
    <tr>
        <th scope="col">Title</th>
        <th scope="col">Author</th>
        <th scope="col">Year</th>
        <th scope="col">Genre</th>
        <th scope="col">Language</th>
<#--        <th scope="col">Status</th>-->
    </tr>
    </thead>
    <tbody>
    <#list books as book>
        <tr class="bg-success">
            <td>${book.title}</td>
            <td>${book.author}</td>
            <td>${book.year}</td>
            <td>${book.genre}</td>
            <td>${book.language}</td>
<#--            <td>${book.state}</td>-->
<#--            <#if book.state>-->
<#--                <td>Свободна</td>-->
<#--            <#else>-->
<#--                <td>Занята</td>-->
<#--            </#if>-->
            <td><a type="button" class="btn btn-dark" href="/book">Info</a></td>
        </tr>
    </#list>
    </tbody>
</table>
</body>
</html>