<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<p><b>Ошибка!</b></p>
<p>Пользователь с таким email уже существует</p>
<a href="/register" class="btn btn-outline-success my-2 my-sm-0">Попробовать Заново</a>

<button></button>
</body>
</html>