<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous"></head>
</head>
<body>
<p><b>Ошибка</b></p>
<p>Неправильный логин или пароль!</p>
<a href="/login" class="btn btn-outline-success my-2 my-sm-0">Попробовать Заново</a>
<p class="title mt-5">Если у вас нет аккаунта вы можете зарегестрироваться по кнопке "Регистрация"</p>
<a href="/register" class="btn btn-outline-success my-2 my-sm-0">Регистрация</a>

</body>
</html>